language: java

jdk:
  - openjdk8

env:
  - TEST_DIR=campanha-service
  - TEST_DIR=time-api
  - TEST_DIR=torcedor-service

install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -f $TEST_DIR/pom.xml

script:
  - mvn test coveralls:report -DrepoToken=$COVERALLS_REPO_TOKEN -B -f $TEST_DIR/pom.xml


cache:
  directories:
    - ~/.m2/repository