eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/    
            
logging:
  file: logs/monitoring.log
  level:
    root: WARN
    # Set INFO to see the allocated port
    org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer: INFO
    org.springframework.boot.context.embedded.undertow.UndertowEmbeddedServletContainer: INFO
    org.springframework.security: DEBUG	    


hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
spring:
  rabbitmq:
    host: rabbitmq

    
---
spring:
  profiles: docker
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
    