server:
  context-path: /campanhas
  port: 8881
endpoints:
  shutdown:
    enabled: true
  restart:
    enabled: true
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/    
feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
  
logging:
  file: logs/campanha-api.log
  level:
    root: INFO

    # Set INFO to see the allocated port
    org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer: INFO
    org.springframework.boot.context.embedded.undertow.UndertowEmbeddedServletContainer: INFO 
    logging.level.org.springframework.web: DEBUG
    br.com.campanha.api: DEBUG
spring:
  rabbitmq:
    host: rabbitmq
---
# Auth-server instance when used on Docker
spring:
  profiles: docker
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/