server:
  port: 8882

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    enabled: false
    fetchRegistry: true
    registerWithEureka: false

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/team
---
# Auth-server instance when used on Docker
spring:
  profiles: docker
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/